package com.yc.favorite.bean;

public class Favorite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.f_label
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private String fLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.f_url
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private String fUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.f_tags
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private String fTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.f_desc
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private String fDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.id
     *
     * @return the value of favorite.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.id
     *
     * @param id the value for favorite.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.f_label
     *
     * @return the value of favorite.f_label
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public String getfLabel() {
        return fLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.f_label
     *
     * @param fLabel the value for favorite.f_label
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setfLabel(String fLabel) {
        this.fLabel = fLabel == null ? null : fLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.f_url
     *
     * @return the value of favorite.f_url
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public String getfUrl() {
        return fUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.f_url
     *
     * @param fUrl the value for favorite.f_url
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setfUrl(String fUrl) {
        this.fUrl = fUrl == null ? null : fUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.f_tags
     *
     * @return the value of favorite.f_tags
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public String getfTags() {
        return fTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.f_tags
     *
     * @param fTags the value for favorite.f_tags
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setfTags(String fTags) {
        this.fTags = fTags == null ? null : fTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.f_desc
     *
     * @return the value of favorite.f_desc
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public String getfDesc() {
        return fDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.f_desc
     *
     * @param fDesc the value for favorite.f_desc
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setfDesc(String fDesc) {
        this.fDesc = fDesc == null ? null : fDesc.trim();
    }
}