package com.yc.favorite.bean;

import java.util.List;

public class Tags {
	
	private List<Favorite> fList;
	public List<Favorite>getfList(){
		return fList;
	}
	public void setfList(List<Favorite> fList) {
		this.fList = fList;
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.t_name
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.t_count
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private Integer tCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.t_name
     *
     * @return the value of tags.t_name
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.t_name
     *
     * @param tName the value for tags.t_name
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.t_count
     *
     * @return the value of tags.t_count
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public Integer gettCount() {
        return tCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.t_count
     *
     * @param tCount the value for tags.t_count
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void settCount(Integer tCount) {
        this.tCount = tCount;
    }
}