package com.yc.favorite.bean;

public class Tf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf.tid
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf.fid
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf.id
     *
     * @return the value of tf.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf.id
     *
     * @param id the value for tf.id
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf.tid
     *
     * @return the value of tf.tid
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf.tid
     *
     * @param tid the value for tf.tid
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf.fid
     *
     * @return the value of tf.fid
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf.fid
     *
     * @param fid the value for tf.fid
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}