package com.yc.favorite.dao;

import com.yc.favorite.bean.Tf;
import com.yc.favorite.bean.TfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TfMapper {
	@Select("select * from tf")
	public List<Tf> queryAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    long countByExample(TfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    int deleteByExample(TfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    int insert(Tf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    int insertSelective(Tf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    List<Tf> selectByExample(TfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    Tf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tf record, @Param("example") TfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    int updateByExample(@Param("record") Tf record, @Param("example") TfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(Tf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf
     *
     * @mbg.generated Thu Aug 01 09:17:39 CST 2019
     */
    int updateByPrimaryKey(Tf record);
}