#JSP配置 
spring:
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: aaaa
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      
  resources:
    staticLocations:
      file:/d:/blog/
    
  mail:
    host: smtp.qq.com
    username: 1256714073@qq.com
    password: zrtaeqqbvzuqjeje
    default-encoding: UTF-8

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

mail:
  fromMail:
    addr: 1256714073@qq.com

logging:
  level:
    com:
      yc: trace
    